<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Spencer Vacuum System Quotation Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'mike@mlindustrialair.com',
		'to' => 'mike@mlindustrialair.com'
	),
	'fields' => array(
		'Email' => array(
			'order' => 9,
			'type' => 'email',
			'label' => 'Contact Email',
			'required' => false,
			'errors' => array(
				'format' => 'Field \'Contact Email\' has an invalid email.'
			)
		),
		'custom_U20313' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Phone Number',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Phone Number\' is required.'
			)
		),
		'custom_U20361' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Contact Person',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Contact Person\' is required.'
			)
		),
		'custom_U20405' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Company Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Company Name\' is required.'
			)
		),
		'custom_U20449' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Fax',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Fax\' is required.'
			)
		),
		'custom_U20493' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Address',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Address\' is required.'
			)
		),
		'custom_U20537' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'City',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'City\' is required.'
			)
		),
		'custom_U20581' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'State',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'State\' is required.'
			)
		),
		'custom_U20625' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Zip code',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Zip code\' is required.'
			)
		),
		'custom_U20713' => array(
			'order' => 10,
			'type' => 'string',
			'label' => 'Type of Vacuum system',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Type of Vacuum system\' is required.'
			)
		),
		'custom_U20757' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'Number of simultaneous users',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Number of simultaneous users\' is required.'
			)
		),
		'custom_U21117' => array(
			'order' => 14,
			'type' => 'string',
			'label' => 'Where is the vacuum source to be located?',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Where is the vacuum source to be located?\' is required.'
			)
		),
		'custom_U21165' => array(
			'order' => 15,
			'type' => 'string',
			'label' => 'Altitude above sea level (Feet)',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Altitude above sea level (Feet)\' is required.'
			)
		),
		'custom_U21209' => array(
			'order' => 16,
			'type' => 'string',
			'label' => 'Ceiling Height (Feet)',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Ceiling Height (Feet)\' is required.'
			)
		),
		'custom_U21253' => array(
			'order' => 17,
			'type' => 'string',
			'label' => 'Electrical Service',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Electrical Service\' is required.'
			)
		),
		'custom_U21297' => array(
			'order' => 18,
			'type' => 'string',
			'label' => 'What is the longest distance from the vacuum source to the last hose connection (Feet)?',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'What is the longest distance from the vacuum source to the last hose connection (Feet)?\' is required.'
			)
		),
		'custom_U21341' => array(
			'order' => 19,
			'type' => 'string',
			'label' => 'Describe the material(s) to be collected with the vacuum system',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Describe the material(s) to be collected with the vacuum system\' is required.'
			)
		),
		'custom_U22153' => array(
			'order' => 21,
			'type' => 'string',
			'label' => 'Estimate volume of material to be collected',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Estimate volume of material to be collected\' is required.'
			)
		),
		'custom_U22197' => array(
			'order' => 22,
			'type' => 'string',
			'label' => 'Time Period',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Time Period\' is required.'
			)
		),
		'custom_U21385' => array(
			'order' => 20,
			'type' => 'checkboxgroup',
			'label' => '\"X\" All that apply concerning the material(s) collected',
			'required' => true,
			'optionItems' => array(
				'Abrasive',
				'Acidic',
				'Moist',
				'Corrosive',
				'Toxic',
				'Hygroscopic',
				'Explosive',
				'Flammable',
				'Attracts Static Charge'
			),
			'errors' => array(
				'required' => 'Field \'\"X\" All that apply concerning the material(s) collected\' is required.',
				'format' => 'Field \'\"X\" All that apply concerning the material(s) collected\' has an invalid value.'
			)
		),
		'custom_U22241' => array(
			'order' => 23,
			'type' => 'checkboxgroup',
			'label' => 'Optional Information (\"X\" appropriate box)',
			'required' => true,
			'optionItems' => array(
				'Primary Collector-Hopper Bottom',
				'Support Frame for Primary Collector',
				'Primary Collector-Hopper Bottom & Legs',
				'Primary Collector-Removable Dirt Can',
				'Tubular Bag Separator-Hopper Bottom',
				'Support Frame for Tubular Bag Separator',
				'Tubular Bag Separator-Hopper Btm & Legs',
				'Tubular Bag Separator-Removable Dirt Can',
				'Stationary Liquid Separator',
				'Portable Liquid Separator (Single user)',
				'Jet Pulse Collector-Hopper Bottom',
				'Support Frame for Jet Pulse Collector',
				'Jet Pulse Collector-Hopper Bottom & Legs',
				'Jet Pulse Collector-Removable Dirt Can',
				'Filter Bags',
				'Cartridge Filters',
				'Electrical Controls Required',
				'Tubing and Fittings Quotation Required',
				'Hose and Tools Quotation Required',
				'Industravac Product',
				'Vacuum Producer'
			),
			'errors' => array(
				'required' => 'Field \'Optional Information (\"X\" appropriate box)\' is required.',
				'format' => 'Field \'Optional Information (\"X\" appropriate box)\' has an invalid value.'
			)
		),
		'custom_U27657' => array(
			'order' => 12,
			'type' => 'checkboxgroup',
			'label' => 'Hose Size',
			'required' => true,
			'optionItems' => array(
				'2 Inches',
				'1-1/2 inches',
				'1-1/4 inches'
			),
			'errors' => array(
				'required' => 'Field \'Hose Size\' is required.',
				'format' => 'Field \'Hose Size\' has an invalid value.'
			)
		),
		'custom_U20889' => array(
			'order' => 13,
			'type' => 'radiogroup',
			'label' => 'System Layout Available?',
			'required' => true,
			'optionItems' => array(
				'Yes',
				'No'
			),
			'errors' => array(
				'required' => 'Field \'System Layout Available?\' is required.',
				'format' => 'Field \'System Layout Available?\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
